export const ESTABLISH_CONNECTION = 'ESTABLISH_CONNECTION';
export const CLOSE_CONNECTION = 'CLOSE_CONNECTION';

export const SET_MP_PROD_RESPONSE = 'SET_MP_PROD_RESPONSE';
export const NOTIFY_MP_PROD_CHANGES = 'NOTIFY_MP_PROD_CHANGES';
export const GET_INIT_PROD_MP_DATA = 'GET_INIT_PROD_MP_DATA';
export const SET_INIT_PROD_MP_DATA = 'SET_INIT_PROD_MP_DATA';

export const SET_API_GATEWAY_PROD_RESPONSE = 'SET_API_GATEWAY_PROD_RESPONSE';
export const NOTIFY_API_GATEWAY_PROD_CHANGES = 'NOTIFY_API_GATEWAY_PROD_CHANGES';
export const GET_INIT_PROD_API_GATEWAY_DATA = 'GET_INIT_PROD_API_GATEWAY_DATA';
export const SET_INIT_PROD_API_GATEWAY_DATA = 'SET_INIT_PROD_API_GATEWAY_DATA';

export const SET_ORG_DASHBOARD_PROD_RESPONSE = 'SET_ORG_DASHBOARD_PROD_RESPONSE';
export const NOTIFY_ORG_DASHBOARD_PROD_CHANGES = 'NOTIFY_ORG_DASHBOARD_PROD_CHANGES';
export const GET_INIT_PROD_ORG_DASHBOARD_DATA = 'GET_INIT_PROD_ORG_DASHBOARD_DATA';
export const SET_INIT_PROD_ORG_DASHBOARD_DATA = 'SET_INIT_PROD_ORG_DASHBOARD_DATA';

export const SET_ACL_PROD_RESPONSE = 'SET_ACL_PROD_RESPONSE';
export const NOTIFY_ACL_PROD_CHANGES = 'NOTIFY_ACL_PROD_CHANGES';
export const GET_INIT_PROD_ACL_DATA = 'GET_INIT_PROD_ACL_DATA';
export const SET_INIT_PROD_ACL_DATA = 'SET_INIT_PROD_ACL_DATA';

export const SET_API_PROD_RESPONSE = 'SET_API_PROD_RESPONSE';
export const NOTIFY_API_PROD_CHANGES = 'NOTIFY_API_PROD_CHANGES';
export const GET_INIT_PROD_API_DATA = 'GET_INIT_PROD_API_DATA';
export const SET_INIT_PROD_API_DATA = 'SET_INIT_PROD_API_DATA';
