export const ESTABLISH_CONNECTION = 'ESTABLISH_CONNECTION';
export const CLOSE_CONNECTION = 'CLOSE_CONNECTION ';

export const START_MP_PROD_LISTEN = 'START_MP_PROD_LISTEN';

export const SET_MP_PROD_RESPONSE = 'SET_MP_PROD_RESPONSE';

export const NOTIFY_MP_PROD_CHANGES = 'NOTIFY_MP_PROD_CHANGES';

export const GET_INIT_PROD_MP_DATA = 'GET_INIT_PROD_MP_DATA';
export const SET_INIT_PROD_MP_DATA = 'SET_INIT_PROD_MP_DATA';
