export const ESTABLISH_CONNECTION = "ESTABLISH_CONNECTION ";
export const CLOSE_CONNECTION = "CLOSE_CONNECTION ";

export const TOGGLE_MP_PROD_LISTEN = "TOGGLE_MP_PROD_LISTEN";
export const SET_MP_PROD_LISTEN = "SET_MP_PROD_LISTEN";

export const TOGGLE_OD_PROD_LISTEN = "TOGGLE_OD_PROD_LISTEN";
export const SET_OD_PROD_LISTEN = "SET_OD_PROD_LISTEN";

export const SET_MP_PROD_RESPONSE = "SET_MP_PROD_RESPONSE";

export const SET_OD_PROD_RESPONSE = "SET_OD_PROD_RESPONSE";
